feat(build-push): migrate to OIDC authentication strategy (#63)
* tweak(build-push): migrate to OIDC authentication strategy

Also bumps action deps

* Incorporate aem-hugo branch changes

* Address review comments

* Reference get-from-vault using SHA

diff --git a/.github/workflows/docs-build-push.yml b/.github/workflows/docs-build-push.yml
--- a/.github/workflows/docs-build-push.yml
+++ b/.github/workflows/docs-build-push.yml
@@ -3,7 +3,11 @@ name: Docs Build Push
 on:
   workflow_call:
     secrets:
-      AZURE_CREDENTIALS:
+      OIDC_CLIENT_ID:
+        required: true
+      OIDC_TENANT_ID:
+        required: true
+      OIDC_SUBSCRIPTION_ID:
         required: true
       AZURE_KEY_VAULT:
         required: true
@@ -64,6 +68,8 @@ env:
   DOMAIN_STAGING: "docs-staging.nginx.com"
   DOMAIN_PROD: "docs.nginx.com"
   DOMAIN_UNIT: "unit.nginx.org"
+  DOMAIN_STAGING_TECHDOCS: "staging.techdocs.f5.com"
+  DOMAIN_PROD_TECHDOCS: "techdocs.f5.com"
 
 jobs:
   checks:
@@ -88,6 +94,10 @@ jobs:
     needs: [checks]
     if: ${{ needs.checks.outputs.forked_workflow == 'false' }}
     runs-on: ubuntu-24.04
+    permissions:
+      id-token: write
+      contents: read
+      issues: write
     outputs: 
       PREVIEW_URL: ${{ steps.summary.outputs.PREVIEW_URL }}
     env:
@@ -123,8 +133,8 @@ jobs:
             echo "DEPLOYMENT_ENV=preview" >> "$GITHUB_ENV"
           fi
 
-          if [[ ! "${DEPLOYMENT_ENV}" =~ ^(dev|staging|prod|preview)$ ]]; then
-            echo "::error::Invalid environment input: ${DEPLOYMENT_ENV}. Must be one of dev, staging, prod, preview"
+          if [[ ! "${DEPLOYMENT_ENV}" =~ ^(dev|staging|prod|preview|staging_techdocs|prod_techdocs)$ ]]; then
+            echo "::error::Invalid environment input: ${DEPLOYMENT_ENV}. Must be one of dev, staging, prod, preview, staging_techdocs, prod_techdocs"
             exit 1
           fi
 
@@ -141,46 +151,63 @@ jobs:
       - name: Set deployment domain
         id: deployment
         run: |
-          case ${DEPLOYMENT_ENV}/${{github.repository}} in
-            dev/*)
+          if [[ "${DEPLOYMENT_ENV}" == "preview" ]] || [[ "${{ github.event.action }}" == "opened" ]] || [[ "${{ github.event.action }}" == "synchronize" ]]; then
+            echo "IS_PREVIEW=true" >> "$GITHUB_ENV"
+          else
+            echo "IS_PREVIEW=false" >> "$GITHUB_ENV"
+          fi
+          
+          # Map environment -> domain + storage prefix
+          case "${DEPLOYMENT_ENV}" in
+            dev)
               DOMAIN="${DOMAIN_DEV}"
+              STORAGE_PREFIX="dev"
               ;;
-            staging/*)
+            staging)
               DOMAIN="${DOMAIN_STAGING}"
+              STORAGE_PREFIX="staging"
               ;;
-            prod/nginx/unit-docs)
-              DOMAIN="${DOMAIN_UNIT}"
-              ;;
-            prod/*)
+            prod)
               DOMAIN="${DOMAIN_PROD}"
+              STORAGE_PREFIX="prod"
               ;;
-            preview/*)
+            staging_techdocs)
+              DOMAIN="${DOMAIN_STAGING_TECHDOCS}"
+              STORAGE_PREFIX="staging_techdocs"
+              ;;
+            prod_techdocs)
+              DOMAIN="${DOMAIN_PROD_TECHDOCS}"
+              STORAGE_PREFIX="prod_techdocs"
+              ;;
+            preview)
               DOMAIN="${DOMAIN_PREVIEW}"
+              STORAGE_PREFIX="dev"
+              ;;
+            *)
+              echo "::error::Unhandled DEPLOYMENT_ENV '${DEPLOYMENT_ENV}'"
+              exit 1
               ;;
           esac
 
           echo "DEPLOYMENT_DOMAIN=${DOMAIN}" >> $GITHUB_ENV
+          echo "STORAGE_PREFIX=${STORAGE_PREFIX}" >> $GITHUB_ENV
 
       - name: Azure login
-        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
+        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
         with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          client-id: ${{ secrets.OIDC_CLIENT_ID }}
+          tenant-id: ${{ secrets.OIDC_TENANT_ID }}
+          subscription-id: ${{ secrets.OIDC_SUBSCRIPTION_ID }}
 
-      - name: Retrieve secrets from Keyvault
-        id: keyvault
-        uses: azure/cli@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2.1.0
+      - name: Retrieve secrets from keyvault
+        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@0fc1fc087a55f75740cebba008010c812b6d0da2 #main
         with:
-          inlineScript: |
-            secrets_get=(resourceGroupName cdnProfileName cdnName accountName)
-            for secret_get in ${secrets_get[@]}
-            do
-              value=$(az keyvault secret show --name $secret_get --vault-name ${{ secrets.AZURE_KEY_VAULT }} --query value --output tsv)
-              echo "::add-mask::$value"
-              echo "$secret_get=$value" >> $GITHUB_OUTPUT
-            done
+          vault-name: ${{ secrets.AZURE_KEY_VAULT }}
+          secret-names: resourceGroupName, cdnProfileName, cdnName, accountName
+          env-names: AZ_RESOURCE_GROUP, AZ_CDN_PROFILE, AZ_CDN, AZ_ACCOUNT
 
       - name: Checkout docs content
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.7.1
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
           fetch-depth: 0 # This is required for hugo Lastmod to function properly
 
@@ -194,7 +221,7 @@ jobs:
         ### Hugo builds
 
       - name: Setup Go
-        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
+        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
         if: inputs.doc_type == 'hugo'
         with:
           go-version: ${{env.GO_VERISON}}
@@ -225,7 +252,7 @@ jobs:
         run: npm ci
 
       - name: Build Hugo for PR preview
-        if: inputs.doc_type == 'hugo' && (github.event.action == 'synchronize' || github.event.action == 'opened' || env.DEPLOYMENT_ENV == 'preview')
+        if: inputs.doc_type == 'hugo' && env.IS_PREVIEW == 'true'
         working-directory: ${{inputs.docs_build_path}}
         run: |
           hugo mod get -v "$THEME_MODULE@$THEME_VERSION"
@@ -233,7 +260,7 @@ jobs:
 
       - name: Build Hugo for environment
         working-directory: ${{inputs.docs_build_path}}
-        if: inputs.doc_type == 'hugo' && env.DEPLOYMENT_ENV != 'preview'
+        if: inputs.doc_type == 'hugo' && env.IS_PREVIEW  != 'true'
         run: |
           hugo mod get "$THEME_MODULE@$THEME_VERSION"
           hugo --gc -e production --baseURL="https://${DEPLOYMENT_DOMAIN}${PRODUCTION_URL_PATH}"
@@ -265,8 +292,8 @@ jobs:
       ### Azure upload
 
       - name: Azure upload PR preview
-        uses: azure/cli@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2.1.0
-        if: github.event.action == 'synchronize' || github.event.action == 'opened' || env.DEPLOYMENT_ENV == 'preview'
+        uses: azure/cli@9eb25b8360668fb0ecbafa808d40e2197b2f5f52 # v3.0.0
+        if: env.IS_PREVIEW == 'true'
         with:
           inlineScript: |
             cd ${{inputs.docs_build_path}} \
@@ -274,38 +301,38 @@ jobs:
                  -s $DOCS_SOURCE_PATH \
                  -d '$web' \
                  --destination-path "dev/${{github.repository}}/previews/${PR_NUMBER}" \
-                 --account-name ${{steps.keyvault.outputs.accountName}} \
+                 --account-name ${{ env.AZ_ACCOUNT }} \
                  --overwrite \
                  --content-cache-control "max-age=3600" \
                  --auth-mode login
 
                  az afd endpoint purge \
-                  --resource-group ${{steps.keyvault.outputs.resourceGroupName}} \
-                  --profile-name ${{steps.keyvault.outputs.cdnProfileName}} \
-                  --endpoint-name ${{steps.keyvault.outputs.cdnName}} \
+                  --resource-group ${{ env.AZ_RESOURCE_GROUP }} \
+                  --profile-name ${{ env.AZ_CDN_PROFILE }} \
+                  --endpoint-name ${{ env.AZ_CDN }} \
                   --domains $DOMAIN_PREVIEW \
                   --content-paths "${PREVIEW_URL_PATH}/*" \
                   --no-wait
 
       - name: Azure upload to specified environment
-        uses: azure/cli@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2.1.0
-        if: env.DEPLOYMENT_ENV != 'preview'
+        uses: azure/cli@9eb25b8360668fb0ecbafa808d40e2197b2f5f52 # v3.0.0
+        if: env.IS_PREVIEW != 'true'
         with:
           inlineScript: |
             cd ${{inputs.docs_build_path}} \
             && az storage blob upload-batch \
                  -s $DOCS_SOURCE_PATH \
                  -d '$web' \
-                 --destination-path "${DEPLOYMENT_ENV}/${{github.repository}}/latest/" \
-                 --account-name ${{steps.keyvault.outputs.accountName}} \
+                 --destination-path "${STORAGE_PREFIX}/${{github.repository}}/latest/" \
+                 --account-name ${{ env.AZ_ACCOUNT }} \
                  --overwrite \
                  --content-cache-control "max-age=3600" \
                  --auth-mode login
 
                az afd endpoint purge \
-                  --resource-group ${{steps.keyvault.outputs.resourceGroupName}} \
-                  --profile-name ${{steps.keyvault.outputs.cdnProfileName}} \
-                  --endpoint-name ${{steps.keyvault.outputs.cdnName}} \
+                  --resource-group ${{ env.AZ_RESOURCE_GROUP }} \
+                  --profile-name ${{ env.AZ_CDN_PROFILE }} \
+                  --endpoint-name ${{env.AZ_CDN }} \
                   --domains $DEPLOYMENT_DOMAIN \
                   --content-paths "${PRODUCTION_URL_PATH}/*" \
                   --no-wait
