Incorporate aem-hugo branch changes

diff --git a/.github/workflows/docs-build-push.yml b/.github/workflows/docs-build-push.yml
--- a/.github/workflows/docs-build-push.yml
+++ b/.github/workflows/docs-build-push.yml
@@ -68,6 +68,8 @@ env:
   DOMAIN_STAGING: "docs-staging.nginx.com"
   DOMAIN_PROD: "docs.nginx.com"
   DOMAIN_UNIT: "unit.nginx.org"
+  DOMAIN_STAGING_TECHDOCS: "staging.techdocs.f5.com"
+  DOMAIN_PROD_TECHDOCS: "techdocs.f5.com"
 
 jobs:
   checks:
@@ -131,7 +133,7 @@ jobs:
             echo "DEPLOYMENT_ENV=preview" >> "$GITHUB_ENV"
           fi
 
-          if [[ ! "${DEPLOYMENT_ENV}" =~ ^(dev|staging|prod|preview)$ ]]; then
+          if [[ ! "${DEPLOYMENT_ENV}" =~ ^(dev|staging|prod|preview|staging_techdocs|prod_techdocs)$ ]]; then
             echo "::error::Invalid environment input: ${DEPLOYMENT_ENV}. Must be one of dev, staging, prod, preview"
             exit 1
           fi
@@ -149,25 +151,46 @@ jobs:
       - name: Set deployment domain
         id: deployment
         run: |
-          case ${DEPLOYMENT_ENV}/${{github.repository}} in
-            dev/*)
+          if [[ "${DEPLOYMENT_ENV}" == "preview" ]] || [[ "${{ github.event.action }}" == "opened" ]] || [[ "${{ github.event.action }}" == "synchronize" ]]; then
+            echo "IS_PREVIEW=true" >> "$GITHUB_ENV"
+          else
+            echo "IS_PREVIEW=false" >> "$GITHUB_ENV"
+          fi
+          
+          # Map environment -> domain + storage prefix
+          case "${DEPLOYMENT_ENV}" in
+            dev)
               DOMAIN="${DOMAIN_DEV}"
+              STORAGE_PREFIX="dev"
               ;;
-            staging/*)
+            staging)
               DOMAIN="${DOMAIN_STAGING}"
+              STORAGE_PREFIX="staging"
               ;;
-            prod/nginx/unit-docs)
-              DOMAIN="${DOMAIN_UNIT}"
-              ;;
-            prod/*)
+            prod)
               DOMAIN="${DOMAIN_PROD}"
+              STORAGE_PREFIX="prod"
               ;;
-            preview/*)
+            staging_techdocs)
+              DOMAIN="${DOMAIN_STAGING_TECHDOCS}"
+              STORAGE_PREFIX="staging_techdocs"
+              ;;
+            prod_techdocs)
+              DOMAIN="${DOMAIN_PROD_TECHDOCS}"
+              STORAGE_PREFIX="prod_techdocs"
+              ;;
+            preview)
               DOMAIN="${DOMAIN_PREVIEW}"
+              STORAGE_PREFIX="dev"
+              ;;
+            *)
+              echo "::error::Unhandled DEPLOYMENT_ENV '${DEPLOYMENT_ENV}'"
+              exit 1
               ;;
           esac
 
           echo "DEPLOYMENT_DOMAIN=${DOMAIN}" >> $GITHUB_ENV
+          echo "STORAGE_PREFIX=${STORAGE_PREFIX}" >> $GITHUB_ENV
 
       - name: Azure login
         uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
@@ -229,7 +252,7 @@ jobs:
         run: npm ci
 
       - name: Build Hugo for PR preview
-        if: inputs.doc_type == 'hugo' && (github.event.action == 'synchronize' || github.event.action == 'opened' || env.DEPLOYMENT_ENV == 'preview')
+        if: inputs.doc_type == 'hugo' && env.IS_PREVIEW == 'true'
         working-directory: ${{inputs.docs_build_path}}
         run: |
           hugo mod get -v "$THEME_MODULE@$THEME_VERSION"
@@ -237,7 +260,7 @@ jobs:
 
       - name: Build Hugo for environment
         working-directory: ${{inputs.docs_build_path}}
-        if: inputs.doc_type == 'hugo' && env.DEPLOYMENT_ENV != 'preview'
+        if: inputs.doc_type == 'hugo' && env.IS_PREVIEW  != 'true'
         run: |
           hugo mod get "$THEME_MODULE@$THEME_VERSION"
           hugo --gc -e production --baseURL="https://${DEPLOYMENT_DOMAIN}${PRODUCTION_URL_PATH}"
@@ -270,7 +293,7 @@ jobs:
 
       - name: Azure upload PR preview
         uses: azure/cli@9eb25b8360668fb0ecbafa808d40e2197b2f5f52 # v3.0.0
-        if: github.event.action == 'synchronize' || github.event.action == 'opened' || env.DEPLOYMENT_ENV == 'preview'
+        if: env.IS_PREVIEW == 'true'
         with:
           inlineScript: |
             cd ${{inputs.docs_build_path}} \
@@ -293,14 +316,14 @@ jobs:
 
       - name: Azure upload to specified environment
         uses: azure/cli@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2.1.0
-        if: env.DEPLOYMENT_ENV != 'preview'
+        if: env.IS_PREVIEW != 'true'
         with:
           inlineScript: |
             cd ${{inputs.docs_build_path}} \
             && az storage blob upload-batch \
                  -s $DOCS_SOURCE_PATH \
                  -d '$web' \
-                 --destination-path "${DEPLOYMENT_ENV}/${{github.repository}}/latest/" \
+                 --destination-path "${STORAGE_PREFIX}/${{github.repository}}/latest/" \
                  --account-name ${{ env.AZ_ACCOUNT }} \
                  --overwrite \
                  --content-cache-control "max-age=3600" \
